MX-16 version
Former-commit-id: 9eff52ae219166ad10741c55cff922cf3a4fa465

diff --git a/initrd/bin/umount-init b/initrd/bin/umount-init
--- a/initrd/bin/umount-init
+++ b/initrd/bin/umount-init
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 PATH=/bin
+ME=${0##*/}
 
 e=$(printf "\e")
  cyan="$e[0;36m";     red="$e[0;31m";      nc="$e[0m"
@@ -51,6 +52,19 @@ final_umount() {
 
 safe_shutdown() {
     local cmd=$1 prompt=${1:-continue}
+
+    if test -e /proc/mounts; then
+        local rootfs=$(sed -nr "s=^([^ ]+) / .*=\1=p" /proc/mounts)
+
+        case $rootfs in
+                  rootfs) ;;
+            aufs|overlay) echo "$ME cannot be use here" >&2
+                          exit 2 ;;
+                       *) echo "$ME must be used on a live system" >&2
+                          exit 3 ;;
+        esac
+    fi
+
     if final_umount; then
         echo "${lt_cyan}Umount successful$nc"
         echo -n "${lt_cyan}Press <Enter> to$white $prompt$nc "
