new iso template matching b1/b2
Former-commit-id: 22d8c6a4bed0c235bf9660dcfc5b378f3c9900b0

diff --git a/initrd/bin/unpack-initrd b/initrd/bin/unpack-initrd
--- a/initrd/bin/unpack-initrd
+++ b/initrd/bin/unpack-initrd
@@ -1,4 +1,4 @@
-#!/live/bin/sh
+#!/bin/bash
 
 # See Documentation/x86/boot.txt in Linux source
 
@@ -6,7 +6,8 @@ ME=${0##*/}
 
 INITRD_FILE=/live/boot-dev/antiX/initrd.gz
 INITRD_DIR=./initrd
-CPIO_OPTS="-o -H newc --owner root:root"
+REPACK_ARGS="-o -H newc --owner root:root --quiet"
+UNPACK_ARGS="-idum --quiet"
 
 
 usage() {
@@ -15,13 +16,16 @@ usage() {
     cat <<Usage
 Usage:  $ME [options]
 
+Unpack and repack the live initrd.gz for antiX and MX.
+
 Options:
   -c  --clear          Delete directory before unpacking
   -d  --dir=<dir>      Unpack in <dir> instead of $INITRD_DIR
-  -i  --initrd=<file>  Unpack <file> instead of $INITRD_FILE
-  -h, --help           Show this usage
-  -p, --pretend        Show commands without running them
-  -r  --repack         Repack the init
+  -f  --from=<file>    Unpack <file> instead of $INITRD_FILE
+  -h  --help           Show this usage
+  -p  --pretend        Show commands without running them
+  -r  --repack         Repack the initrd
+  -q  --quiet          Don't say anything
   -v  --verbose        Show commands in addition to running them
 Usage
 
@@ -35,10 +39,11 @@ eval_argument() {
                -dir|d) INITRD_DIR=$val                 ;;
                -dir=*) INITRD_DIR=$val                 ;;
               -help|h) usage                           ;;
-            -initrd|i) INITRD_FILE=$val                ;;
-            -initrd=*) INITRD_FILE=$val                ;;
+              -from|f) INITRD_FILE=$val                ;;
+              -from=*) INITRD_FILE=$val                ;;
            -pretend|p) PRETEND=true                    ;;
             -repack|r) REPACK=true                     ;;
+             -quiet|q) QUIET=true                      ;;
            -verbose|v) VERBOSE=true                    ;;
                     *) fatal "Unknown parameter -$arg" ;;
     esac
@@ -47,7 +52,7 @@ eval_argument() {
 takes_param() {
     case $1 in
         -dir|[d]) return 0 ;;
-     -initrd|[i]) return 0 ;;
+       -from|[f]) return 0 ;;
     esac
     return 1
 }
@@ -63,8 +68,10 @@ main() {
     [ $# -gt 0 ] && fatal "Unexpected arguments: %s" "$*"
 
     if [ "$REPACK" ]; then
+        qsay "Repack: %s ---> %s" "$(pq ${INITRD_DIR%/}/)" "$(pq $INITRD_FILE)"
         repack_initrd "$INITRD_FILE" "$INITRD_DIR"
     else
+        qsay "Unpack: %s ---> %s" "$(pq $INITRD_FILE)" "$(pq ${INITRD_DIR%/}/)"
         unpack_initrd "$INITRD_FILE" "$INITRD_DIR"
     fi
 
@@ -91,7 +98,7 @@ unpack_initrd() {
 
     cmd mkdir -p "$dir" || fatal "Could not make directory %s" "$dir"
 
-    cmd gunzip -c "$file" | (cd "$dir" && cmd cpio -idum) || fatal "Unpack failed"
+    cmd gunzip -c "$file" | (cd "$dir" && cmd cpio $UNPACK_ARGS) || fatal "Unpack failed"
 }
 
 repack_initrd() {
@@ -102,10 +109,11 @@ repack_initrd() {
     local targ_dir=$(dirname "$file")
     cmd mkdir -p "$targ_dir"
 
-    (cd "$dir" && cmd find . | grep -v "^\./\." | cmd cpio $CPIO_OPTS) \
-        | gzip -9 | cmd write_file "$file" 
+    (cd "$dir" && cmd find . | grep -v "^\./\." | cmd cpio $REPACK_ARGS) \
+        | gzip -9 | cmd write_file "$file"
 
-    (cd "$targ_dir" && cmd md5sum "$(basename "$file")" | cmd write_file "$file.md5")
+    local fname=$(basename $file)
+    (cd "$targ_dir" && cmd md5sum "$(basename "$fname")" | cmd write_file "$fname.md5")
 }
 
 empty_dir() {
@@ -182,11 +190,37 @@ read_params() {
     done
 }
 
+qsay() {
+    [ "$QUIET" ] && return
+    local fmt=$1
+    shift
+    printf "$m_co$fmt$nc_co\n" "$@"
+}
+
 fatal() {
     local fmt=$1; shift
-    printf "$ME fatal error: $fmt\n" "$@" >&2
+    printf "$ME$err_co fatal error:$warn_co $fmt\n" "$@" >&2
     exit 2
 }
 
+pq()  { echo "$hi_co$*$m_co"      ;}
+
+set_colors() {
+   local e=$(printf "\e")
+
+         black="$e[0;30m" ;    blue="$e[0;34m" ;    green="$e[0;32m" ;    cyan="$e[0;36m" ;
+           red="$e[0;31m" ;  purple="$e[0;35m" ;    brown="$e[0;33m" ; lt_gray="$e[0;37m" ;
+       dk_gray="$e[1;30m" ; lt_blue="$e[1;34m" ; lt_green="$e[1;32m" ; lt_cyan="$e[1;36m" ;
+        lt_red="$e[1;31m" ; magenta="$e[1;35m" ;   yellow="$e[1;33m" ;   white="$e[1;37m" ;
+         nc_co="$e[0m"    ;   brown="$e[0;33m" ;
+
+           m_co=$cyan
+          hi_co=$white
+          err_co=$red
+         bold_co=$yellow
+         warn_co=$yellow
+}
+
+set_colors
 main "$@"
 
