new antiX  live with rescue menus
Former-commit-id: d334817da50d3f69f7a86dab24afdbfeb18b11bd

diff --git a/initrd/etc/init.d/live-bootsave b/initrd/etc/init.d/live-bootsave
--- a/initrd/etc/init.d/live-bootsave
+++ b/initrd/etc/init.d/live-bootsave
@@ -1,9 +1,17 @@
 #!/live/bin/sh
 
+#==============================================================================
+# Update the bootloader configurations to save the current boot parameters
+# as weill as parameters selected by the text menus.
+#
+# The actual saving is done by grub2-save and gfxsave.
+#
+# The tricky part is if encryption or frugal were used then we need to mount
+# the BIOS boot partition and update the bootloaders there.
+#==============================================================================
 export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/live/bin
 
-BIOS_UUID_FNAME="bios-dev-uuid"
-UEFI_UUID_FNAME="esp-uuid"
+BOOT_UUID_FNAME="bios-dev-uuid"
 
 . /live/lib/live-init-utils.sh
 
@@ -43,68 +51,58 @@ do_start() {
     echo_script "Possibly saving boot parameters" $0
     get_real_vga_code "$vga_ask" "$gfx_cmd"
 
-    [ -n "$gfx_cmd"   ] && do_gfxsave
-    [ -n "$boot_save" ] && do_boot_save
-}
-
-do_gfxsave() {
-
-    export CMDLINE
-    export GFX_LOG_FILE=/var/log/live/gfxsave.log
-
     . $INITRD_OUT
 
-    local bios_uuid_file="$SQFILE_DIR/$BIOS_UUID_FNAME"
-
-    local dir=$BIOS_MP/boot
-
-    if test -r $bios_uuid_file; then
-        local bios_uuid=$(cat $bios_uuid_file | head -n1 2>/dev/null)
-        [ -n "$bios_uuid" ] && mount_boot_dev "$bios_uuid" $BIOS_MP
-        dir=$ROOT_MP/boot
-    fi
-
-    test -d $dir || dir=$BOOT_MP/boot
-    test -d $dir || return
-
-    local dev=$(df -P $dir | tail -n1 | cut -d" " -f1)
-    echo_live "bootloader device: $(pquote $dev)"
-
-    mount -o remount,rw ${dir%/boot}
-
-    local script=/live/bin/gfxsave
+    [ -n "$gfx_cmd$boot_save" ] || return
 
     if ! [ -e /live/config/remasterable ]; then
         echo_live "Can't update %s on read-only boot media" "$(pquote gfxboot)"
-        return
+        return 1
     fi
 
-    $script $dir $gfx_cmd
+    # Start with the default mountpoint at /live/boot-dev
+    BOOT_LOADER_MP=$BOOT_MP
+
+    # Change to /live/bios if needed (changed the called scripts)
+    local uuid_file="$SQ_FILE_DIR/$BOOT_UUID_FNAME"
+    if ! mount_boot_partition "$uuid_file"; then
+        error "Could not mount the BIOS boot partition"
+        exit 1
+    fi
+
+    if [ -n "$gfx_cmd" ]; then
+        local script=/live/bin/gfxsave
+        local dir=$BOOT_LOADER_MP/boot
+        local env="GFX_LOG_FILE=/var/log/live/gfxsave.log VERBOSE=3"
+        #echo $script $dir $gfx_cmd
+        env $env $script "$dir" $gfx_cmd
+    fi
+
+    if [ -n "$boot_save" ]; then
+        #echo grub2-save $BOOT_LOADER_MP
+        grub2-save $BOOT_LOADER_MP
+    fi
+
+    sync
+
+    #[ -n "$TO_UMOUNT" ] && umount "$TO_UMOUNT"
+
 }
 
-do_boot_save() {
-    . /live/config/initrd.out
+#------------------------------------------------------------------------------
+# Mount out bios/boot partition if we were encrypted or frugal
+#------------------------------------------------------------------------------
+mount_boot_partition() {
+    local uuid_file=$1
 
-    if [ "$BOOT_FSTYPE" = vfat ]; then
-        grub2-save $BOOT_MP
-    fi
+    # If there is no uuid file then proceed as normal
+    test -r "$uuid_file" || return 0
 
-    local uuid dir uuid_file name=$UEFI_UUID_FNAME
-    for dir in $SQFILE_DIR $BOOT_MP; do
-        test -r $dir/$name || continue
-        uuid_file=$dir/$name
-    done
-    test -r $uuid_file || return
-    read uuid 2>/dev/null <$uuid_file
-    [ ${#uuid} -gt 0 ] || return
+    echo "uuid file: $uuid_file"
 
-    local esp_mp=/live/esp
-    mkdir -p $esp_mp
-    mount --uuid $uuid $esp_mp
-    mountpoint -q $esp_mp || return
-    grub2-save $esp_mp
-    sync
-    umount $esp_mp
+    local boot_uuid=$(cat $uuid_file | head -n1 2>/dev/null)
+    echo "boot uuid; $boot_uuid"
+    mount_boot_dev "$boot_uuid" $BIOS_MP || return 1
 }
 
 #------------------------------------------------------------------------------
@@ -204,11 +202,11 @@ old_get_real_vga_code() {
 
 
 #------------------------------------------------------------------------------
-# Mount boot device for case of frugal install
+# Mount boot device for case of frugal install or encrypted
+# Set BOOT_LOADER_MP to the mount point
 #------------------------------------------------------------------------------
 mount_boot_dev() {
     uuid=$1  mp=$2
-    ROOT_MP=
 
     debug "uuid=$uuid  mp=$mp"
 
@@ -226,8 +224,8 @@ mount_boot_dev() {
 
     local existing_mp=$(grep "^$boot_dev " /proc/mounts | cut -d" " -f2)
     debug "existing_mp=$existing_mp"
-    if [ "$existing_mp" ]; then
-        ROOT_MP=$existing_mp
+    if [ -n "$existing_mp" ]; then
+        BOOT_LOADER_MP=$existing_mp
         return 0
     fi
 
@@ -237,14 +235,16 @@ mount_boot_dev() {
         echo_live "Could not remount boot device"
         return 1
     fi
+    TO_UMOUNT="$mp"
 
-    ROOT_MP=$mp
+    BOOT_LOADER_MP=$mp
     return 0
 }
 
 debug() { return; echo "db: $*"; }
 
 echo_cmd() { echo " > $*" >/dev/null ; "$@" ; }
+
 main "$@" 2>&1 | tee -a $INIT_LOG_FILE
 
 exit 0
